CREATE TABLE IF NOT EXISTS account_levels (
  account_level VARCHAR(255) NOT NULL PRIMARY KEY,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) default charset utf8 ENGINE = INNODB;

INSERT
  IGNORE INTO account_levels (account_level)
VALUES
  ('DEFAULT');

CREATE TABLE IF NOT EXISTS accounts (
    account_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    account_name VARCHAR(255) UNIQUE NOT NULL,
    account_level VARCHAR(255) DEFAULT 'DEFAULT',
    is_current TINYINT(1) NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_level) REFERENCES account_levels (account_level) ON UPDATE CASCADE ON DELETE RESTRICT
  ) default charset utf8 ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS user_roles (
    user_role VARCHAR(255) NOT NULL PRIMARY KEY,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  ) default charset utf8 ENGINE = INNODB;

INSERT
  IGNORE INTO user_roles (user_role)
VALUES
  ('ADMIN'),
  ('ACCOUNT_USER');

CREATE TABLE IF NOT EXISTS app_users (
    app_user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) UNIQUE NOT NULL,
    secret VARCHAR(255) UNIQUE NOT NULL,
    user_role VARCHAR(255) NOT NULL DEFAULT 'ACCOUNT_USER',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_role) REFERENCES user_roles (user_role) ON UPDATE CASCADE ON DELETE RESTRICT
  ) default charset utf8 ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS account_users (
    account_user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    account_id INT NOT NULL,
    app_user_id INT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts (account_id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (app_user_id) REFERENCES app_users (app_user_id) ON UPDATE CASCADE ON DELETE CASCADE
  ) default charset utf8 ENGINE = INNODB;
